### ISSUE TITLE
XIOS: Add File I/O To & From XIOS Grid/Axis

### ISSUE THREAD

**Issue by a-smith-github** [nextsimhub/nextsimdg#291]
This is a sub-feature of issue #218 tracking adding the file I/O capability of the XIOS class

We need to be able to write restart files via XIOS using data stored within the XIOS Grid/Axis framework using XIOS Library calls. 

This requires Issues #293 and #292 

For the XIOS Integration, see the [design spec](https://github.com/nextsimdg/nextsimdg/wiki/XIOS-Integration) or the [master pull request](https://github.com/nextsimhub/nextsimdg/pull/265)

**Comment by einola** [comment]
This issue should target the diagnostics files rather than restart files. Diagnostic output is the main reason for us to use XIOS because writing and reading restart files are much less frequent and always contain the same variables, so most of the "nice" features of XIOS are not needed.

So, we should prioritise diagnostic outputs for XIOS and leave restart I/O to the native functionality that already exists. We can then return to the question of XIOS vs. native I/O for restart files later.

**Comment by jwallwork23** [comment]
Closed by #496.
