### ISSUE TITLE
Add information about updating the documentation

### ISSUE THREAD

**Issue by MarionBWeinzierl** [nextsimhub/nextsimdg#436]
Major code changes may require updates or changes of the [documentation on readthedocs](https://nextsim-dg.readthedocs.io/en/latest/index.html), so that this stays in line with the code. 

Therefore, we need information in the README on how update the docs, and also when to update it (change on main? change on develop?). 

@auraoupa , are you able to provide this information, and potentially access to readthedocs, if needed?

**Comment by auraoupa** [comment]
readthedocs documentation is managed on the docs branch and in the docs repo, that is why when you click on "Edit on github" it will bring you there. Modifying the docs branch will then trigger the building, and you are able to see the outcome here : https://readthedocs.org/projects/nextsim-dg/builds/

Also there is an automatic documentation built with doxygen that is managed with a [github workflow](.github/workflows/doxygen.yml) and is visible here : https://nextsimhub.github.io/nextsimdg/index.html

I will modify soon the README to mention all of this in the front page

**Comment by MarionBWeinzierl** [comment]
Done in #445

**Comment by TomMelt** [comment]
@auraoupa , do you have any instructions on how to build the readthedocs docs locally? Or even the doxygen?

**Comment by auraoupa** [comment]
Theoretically it should be possible but I've never done it, because of all the automation that is hidden in readthedoc and the automatic doxygen run that we do in this [github workflow](https://github.com/nextsimhub/nextsimdg/blob/develop/.github/workflows/doxygen.yml) 
The documentation is developped in the docs branch so it is easy to reverse a wrong manipulation, but the output will change live which is not great for sure. 
@stephanieleroux do you have more insights on this matter ?

**Comment by TomMelt** [comment]
Also is it possible to build the documentation for two branches (via `readthedocs`) i.e., `main` and `develop` instead of just `main`.

**Comment by auraoupa** [comment]
Actually it is synchronized with the ```docs``` branch not ```main``` and I could not find a way to synchronize with multiple branches when I looked for it. That is why I rebase the ```docs``` branch from ```develop``` from time to time
