### ISSUE TITLE
Resolve question about MPI thermodynamics parallelisation on RectGrid and ParGrid

### ISSUE THREAD

**Issue by MarionBWeinzierl** [nextsimhub/nextsimdg#442]
The MPI parallelisation work in #331has been done for the Rectangular Grid so far, not for the Parametric Grid. The simulations, however, are all run on the Parametric Grid, the RectGrid is mainly used for testing. Extending the MPI parallelisation the the ParGrid would mean a lot of code duplication. There are three options, the first of which is not desirable from a software engineering perspective:
- Do the same parallelisation for the ParGrid, accepting the code duplication. (not nice)
- Move the parallelisation over to the ParGrid and get rid of the RectGrid
  - This would have a number of implications, such as adapting the tests and regenerating NetCDF files.
- Create a parent class AbstractGrid (or so) from which both ParGrid and RectGrid inherit, and move the parallelisation there.
  - This will probably be the most involved and time-consuming of the options, but also (probably) the most elegant.  

We need to make a decision on how to go forward with this.

**Comment by timspainNERSC** [comment]
> * Move the parallelisation over to the ParGrid and get rid of the RectGrid
>    * This would have a number of implications, such as adapting the tests and regenerating NetCDF files.

The number of implications it would have is 2. The restart files `init_rect20x30.nc` and `init_rect30x30.nc` would have to be regenerated from updated scripts. Since these binary files are moving out of the repo Real Soon Now™, this should not be a problem. There is an intention to use the `30x30` test as a very quick , basic integration test, but this is not currently implemented, and could be equally easily be done from a future `parametric_rectangular` version of the file.

Strong vote for option 2.

**Comment by MarionBWeinzierl** [comment]
@einola , do you have an opinion here? If you do not contradict we'll go with @timspainNERSC 's vote.

**Comment by einola** [comment]
I agree with @timspainNERSC. We can go ahead with option 2.
